# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcf15173ca91233b6c351057a802a7dadce678193d12428d43bbc66c04a377e1e64352e3945b085fc3bd2c76735ed6e115992c4bfa612fab0243e6d9943c9acd

test:
  secret_key_base: 5cd2cbda6d638f0a6a6e30cc9e5af9c1346bb6bc472434ebebd30761bab530acc205f08c9b53f32e37602076a2c46e7bdc15e3d0bbf9b3c4a18a8e60997e4b0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
